# -*- coding: utf-8 -*-
"""min_and_max.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O42V5rgu72wu6qSZubPJMNvDYoFckHpW

Min Max Algorithm
"""

def find_min_and_max(arr, low, high):
    # If there is only one element
    if low == high:
        return arr[low], arr[low]

    # If there are two elements
    if high == low + 1:
        if arr[low] < arr[high]:
            return arr[low], arr[high]
        else:
            return arr[high], arr[low]

    # If there are more than two elements
    mid = (low + high) // 2
    min1, max1 = find_min_and_max(arr, low, mid)
    min2, max2 = find_min_and_max(arr, mid + 1, high)

    # Combine the results
    return min(min1, min2), max(max1, max2)

# Example usage
arr = [3, 5, 1, 2, 4, 8, 6]
low = 0
high = len(arr) - 1
min_val, max_val = find_min_and_max(arr, low, high)

print(f"Minimum value: {min_val}")
print(f"Maximum value: {max_val}")

