# -*- coding: utf-8 -*-
"""pattern-finding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Fp8Y9qwNix8kK3Lk36jf5W8Eb2r85Cv
"""

def search(pat, txt):
    m = len(pat)
    n = len(txt)

    # Loop through the text
    for i in range(n - m + 1):
        # Check if the current substring matches the pattern
        if txt[i:i + m] == pat:
            print(f"Pattern found at index {i}")

# Example usage
txt = "THIS IS A TEST TEXT"
pat = "TEST"

search(pat, txt)

